add version workflow file

diff --git a/.github/workflows/2.yml b/.github/workflows/2.yml
--- a/.github/workflows/2.yml
+++ b/.github/workflows/2.yml
@@ -1,56 +1,60 @@
-name: Run Checks on PR
+name: Version Changes to the Main Branch
 
 on:
-  pull_request:
+  push:
     branches:
       - main
-
-permissions:
-  actions: write
-  checks: write
-  contents: read
-  security-events: write
-  pull-requests: write
-
-env:
-  CI: true
-  SITE_DIR: site
-  TETRIS_APP_HOST: "127.0.0.1"
-  TETRIS_APP_PORT: "8080"
-  TETRIS_APP_PATH: "github-devsecops-fundamentals"
+  workflow_dispatch: {}
 
 jobs:
-  quality-checks:
+  version-main-branch-changes:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-
-      - uses: actions/setup-python@v4
+      - uses: actions/create-github-app-token@v1
+        id: generate-app-token
         with:
-          python-version: 3.12
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 20
+          app-id: ${{ vars.APP_ID_ACTIONS_ASSISTANT }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY_ACTIONS_ASSISTANT }}
 
-      - name: Install Dependencies
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          token: ${{ steps.generate-app-token.outputs.token }}
+
+      - name: Get last version number
+        id: get_last_version
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.ci.txt
-          npm ci
+          # Retrieve the last git tag, as we will only be processing one delivery line.
+          last_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
+          echo "Last version is $last_version"
+          echo "last_version=$last_version" >> "$GITHUB_OUTPUT"
 
-      - name: Build
+      - name: Get new version number
+        id: get_new_version
         run: |
-          python -m mkdocs build --clean --strict --verbose --site-dir '${{ env.SITE_DIR }}'
+          major=$(echo $last_version | cut -d. -f1)
+          minor=$(echo $last_version | cut -d. -f2)
+          patch=$(echo $last_version | cut -d. -f3)
 
-  security-checks:
-    runs-on: ubuntu-latest
-    needs: quality-checks
-    continue-on-error: true
-    steps:
-      - uses: actions/checkout@v3
+          new_patch=$((patch+1))
 
-      - name: Dependency Review
-        uses: actions/dependency-review-action@v3
-        with:
-          config-file: >-
-            ./.github/dependency-review-config.yml
+          new_version="$major.$minor.$new_patch"
+
+          echo "New version is $new_version"
+          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
+        env:
+          last_version: ${{ steps.get_last_version.outputs.last_version }}
+
+      - name: Create tag for the new version
+        run: |
+          git config --global user.name "${GITHUB_ACTOR}"
+          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
+
+          if git tag -a "$new_version" -m "Version $new_version"; then
+            git push --follow-tags origin "$new_version"
+          else
+            echo "Failed to create tag $new_version, it probably already exists"
+          fi
+        env:
+          new_version: ${{ steps.get_new_version.outputs.new_version }}-release
